### ISSUE TITLE
LvL 9 Abilities

### ISSUE THREAD

**Issue by mellscult** [soulboythree/MyHeroUltraRumbleCheatTable#1]
Upon using this option the game freezes and eventually kicks you out of the match you're on, is there any fix? I know the table says its made for the gamepass version but that version is only available for consoles so I am a little confused about it.

**Comment by Envyxelse** [comment]
yea i dont think it works and have no clue what he means by "gamepass version"

**Comment by soulboythree** [comment]
I believe the game is only on steam for pc.... but I do believe I fixed the level 9 abilities. I haven't experienced getting kicked myself but I'll see what people say once I release v4

**Comment by Envyxelse** [comment]
none of them work and all it does is crash the game

**Comment by tuvvvvv** [comment]
> none of them work and all it does is crash the game

made an account just to tell you that if you're crashing you just don't know how to properly use ct or his table, because it works perfectly fine.
